"""empty message

Revision ID: 06e1f43b834c
Revises: 203460c77f6c
Create Date: 2020-12-13 13:00:21.065861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e1f43b834c'
down_revision = '203460c77f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('date', sa.String(length=100), nullable=False))
    op.add_column('projects', sa.Column('prio', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'prio')
    op.drop_column('projects', 'date')
    # ### end Alembic commands ###
