"""empty message

Revision ID: 203460c77f6c
Revises: f9d68a864442
Create Date: 2020-12-13 11:11:05.092679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203460c77f6c'
down_revision = 'f9d68a864442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('link', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'link')
    # ### end Alembic commands ###
