"""empty message

Revision ID: 927f0ec27a26
Revises: 06e1f43b834c
Create Date: 2020-12-13 13:39:55.211576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927f0ec27a26'
down_revision = '06e1f43b834c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('link2', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'link2')
    # ### end Alembic commands ###
